version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.8-node-browsers
    steps:
      - checkout
      - run:
          name: set up env
          command: |
            cp .env.testing.example .env
      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:
          name: composer install
          command: |
            composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: key generate
          command: |
            php artisan key:generate
      - run:
          name: add phpcs
          command: |
            composer global require "squizlabs/php_codesniffer=*"
      - run:
          name: add standard
          command: |
            git clone https://github.com/wataridori/framgia-php-codesniffer.git ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Framgia
      - run:
          name: config installed path
          command: ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Framgia
      # run test
      - run:
          name: check phpcs
          command: |
            sudo ~/.composer/vendor/bin/phpcs --standard=Framgia app --ignore=*/app/Lib/*
      - run:
          name: unit test
          command: |
            phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report
  deploy_development:
    docker:
      - image: framgiaciteam/deb-deploy:7.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e8:d9:fb:2a:dd:a7:fe:eb:d2:b3:ad:ec:d6:23:b8:d1"
      # - run: |
      #     echo '|1|J8kUwIkKAzdz3RYhnJc4C6fCEZY=|IWIMM8uvXQHFoLeBJdTi5qpP/Vw= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLAHYBw+jWGIbUgSSU9iK50KYzdnuocM+J+nljHpJh22xpw1+GDh054uOun1PM+1LM46hNKbIjVpzoSMkS1ca6I=' >> ~/.ssh/known_hosts
      - checkout
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            mv deployer.phar /usr/local/bin/dep
            chmod +x /usr/local/bin/dep
      - run:
          name: Deploy Develop to development
          command: |
            if [ -z `ssh-keygen -F '143.110.209.111'` ]; then
                ssh-keyscan -H '143.110.209.111' >> ~/.ssh/known_hosts
            fi
            dep deployer development
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold_approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_development:
          requires:
            - hold_approval
          filters:
            branches:
              only: master
